---
job: "extension"
config:
  name: "moyuxiugou_v1"
  process:
    - type: "diffusion_trainer"
      training_folder: "/root/ai-toolkit/output"
      sqlite_db_path: "./aitk_db.db"
      device: "cuda"
      trigger_word: null
      performance_log_every: 10
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
        conv: 16
        conv_alpha: 16
        lokr_full_rank: true
        lokr_factor: -1
        network_kwargs:
          ignore_if_contains: []
      save:
        dtype: "bf16"
        save_every: 250
        max_step_saves_to_keep: 5
        save_format: "diffusers"
        push_to_hub: false
      datasets:
        - folder_path: "/root/ai-toolkit/datasets/moyuxiugou_v1"
          mask_path: null
          mask_min_value: 0.1
          default_caption: ""
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          cache_latents_to_disk: false
          is_reg: false
          network_weight: 1
          resolution:
            - 1024
          controls: []
          shrink_video_to_frames: true
          num_frames: 1
          flip_x: false
          flip_y: false
          num_repeats: 1
          control_path_1: null
          control_path_2: null
          control_path_3: null
      train:
        batch_size: 1
        bypass_guidance_embedding: false
        steps: 6000
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        timestep_type: "weighted"
        content_or_style: "balanced"
        optimizer_params:
          weight_decay: 0.0001
        unload_text_encoder: false
        cache_text_embeddings: false
        lr: 0.0001
        ema_config:
          use_ema: false
          ema_decay: 0.99
        skip_first_sample: false
        force_first_sample: false
        disable_sampling: false
        dtype: "bf16"
        diff_output_preservation: false
        diff_output_preservation_multiplier: 1
        diff_output_preservation_class: "person"
        switch_boundary_every: 1
        loss_type: "mse"
      logging:
        log_every: 1
        use_ui_logger: true
      model:
        name_or_path: "black-forest-labs/FLUX.2-klein-base-9B"
        quantize: true
        qtype: "qfloat8"
        quantize_te: true
        qtype_te: "qfloat8"
        arch: "flux2_klein_9b"
        low_vram: true
        model_kwargs:
          match_target_res: false
        layer_offloading: false
        layer_offloading_text_encoder_percent: 1
        layer_offloading_transformer_percent: 1
      sample:
        sampler: "flowmatch"
        sample_every: 250
        width: 1024
        height: 1024
        samples:
          - prompt: "moyuxiugou, fluffy white dog mascot, anthropomorphic, blue scarf, sitting in front of the desk. His eyes half-closed, looking sleepy, he's holding a navy blue coffee cup. On the desk, there's a silver laptop with a bone icon, a few colorful sticky notes, and a black sign with Chinese text. In the background, there's a blurred office environment with posters. Film lighting, detailed office setting, 8k resolution."
          - prompt: "moyuxiugou, fluffy white dog mascot, anthropomorphic, blue scarf. He's comfortably leaning against an office chair, his fluffy paws resting on the desk. Though his heavy bags under the eyes suggest he's a bit tired, a smile is still etched on his lips. He's adorned with a blue name tag. On the wooden desk, there's a laptop with a bone emblem, a pile of scattered papers, and a blue toy fish. The background is a blurred modern office setting. Cinematic lighting, extremely fine hair texture, and vibrant blue and white tones."
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 30
        num_frames: 1
        fps: 1
meta:
  name: "[name]"
  version: "1.0"
